# Generated by Django 3.2.5 on 2021-07-17 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0002_auto_20210717_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='category',
            field=models.ManyToManyField(related_name='categories', to='root.Category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.TextField(max_length=50),
        ),
    ]
