# Generated by Django 3.2.5 on 2021-07-24 05:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import root.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('root', '0003_auto_20210724_0944'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to=root.models.user_avatar_path)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('bookmarks', models.ManyToManyField(blank=True, related_name='users_bookmark', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
