# Generated by Django 3.2.5 on 2021-07-29 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0005_auto_20210729_1150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adv',
            old_name='sub_category',
            new_name='sub_cat',
        ),
        migrations.RemoveField(
            model_name='adv',
            name='category',
        ),
    ]
