# Generated by Django 3.2.5 on 2021-07-25 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0006_advert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, related_name='users_bookmark', to='root.Advert'),
        ),
    ]
