# Generated by Django 3.2.5 on 2021-07-30 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0007_prof_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='prof',
            name='city',
            field=models.TextField(blank=True, null=True),
        ),
    ]
