# Generated by Django 3.2.5 on 2021-08-03 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0009_rename_sub_cat_adv_sub_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adv',
            name='sub_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.cat'),
        ),
        migrations.DeleteModel(
            name='Sub_cat',
        ),
    ]
