# Generated by Django 3.2.5 on 2021-08-03 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0011_rename_sub_name_adv_name_cat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adv',
            old_name='name_cat',
            new_name='sub_name',
        ),
    ]
