# Generated by Django 3.2.5 on 2021-08-03 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0012_rename_name_cat_adv_sub_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adv',
            old_name='sub_name',
            new_name='name_cat',
        ),
    ]
