# Generated by Django 3.2.5 on 2021-08-16 06:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('root', '0014_auto_20210816_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='adv',
            name='bookmark',
            field=models.ManyToManyField(blank=True, related_name='bookmark', to=settings.AUTH_USER_MODEL),
        ),
    ]
