# Generated by Django 3.2.5 on 2021-08-23 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0015_adv_bookmark'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adv',
            options={'verbose_name': 'Объявление', 'verbose_name_plural': 'Объявления'},
        ),
        migrations.AlterModelOptions(
            name='cat',
            options={'verbose_name': 'Раздел', 'verbose_name_plural': 'Разделы'},
        ),
        migrations.AlterModelOptions(
            name='prof',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.RemoveField(
            model_name='adv',
            name='bookmark',
        ),
    ]
