# Generated by Django 3.2.5 on 2021-08-22 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0016_auto_20210822_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adv',
            name='bookmark',
        ),
        migrations.AlterField(
            model_name='prof',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
