# Generated by Django 3.2.5 on 2021-07-28 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0002_auto_20210728_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_cat',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='root.cat'),
            preserve_default=False,
        ),
    ]
