# Generated by Django 3.2.5 on 2021-07-29 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0004_remove_cat_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cat',
            old_name='category_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='sub_cat',
            old_name='category',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='sub_cat',
            old_name='sub_category_name',
            new_name='sub_name',
        ),
        migrations.RemoveField(
            model_name='sub_cat',
            name='code',
        ),
    ]
