# Generated by Django 3.2.5 on 2021-07-30 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0006_auto_20210729_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='prof',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
