# Generated by Django 3.2.5 on 2021-08-03 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0008_prof_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adv',
            old_name='sub_cat',
            new_name='sub_name',
        ),
    ]
