# Generated by Django 3.2.5 on 2021-08-03 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0010_auto_20210803_1328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adv',
            old_name='sub_name',
            new_name='name_cat',
        ),
    ]
