# Generated by Django 3.2.5 on 2021-08-16 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0013_rename_sub_name_adv_name_cat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prof',
            name='bookmarks',
        ),
        migrations.AlterField(
            model_name='adv',
            name='date_pub',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
