# Generated by Django 3.2.5 on 2021-08-23 11:44

from django.db import migrations, models
import root.validators


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0016_auto_20210823_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prof',
            name='city',
            field=models.TextField(blank=True, null=True, validators=[root.validators.validate_num]),
        ),
    ]
